Opr 10 germline sv
hartwigmedical/oncoact pull request #14
Opened 2023-08-03 13:27 UTC by LiekeSchoenmaker

Support all the SV germline events in ROSE/PROTECT/Patient reporter

2023-08-04 07:48 UTC, KasperWolsink99 commented on common/src/main/java/com/hartwig/oncoact/copynumber/ReportableCNVFactory.java
> +            result.add(ImmutablePurpleGainLoss.builder()
I

2023-08-04 08:59 UTC, KasperWolsink99 requested changes
Added some comments :) feel free to ask me if you need any additional explanation or help on some comments.

2023-08-04 08:59 UTC, KasperWolsink99 commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
> +import com.google.common.annotations.VisibleForTesting;
This import is obsolete

2023-08-04 08:59 UTC, KasperWolsink99 commented on common/src/test/java/com/hartwig/oncoact/copynumber/ReportableCNVFactoryTest.java
> +public class ReportableCNVFactoryTest {
The tests in this class don't really do anything to test the ReportableCNVFactory. (The tests in their current form look like they are focussed on testing the behavior of the Lists::newArrayList method which we don't have to test)

2023-08-04 08:59 UTC, KasperWolsink99 commented on common/src/test/java/com/hartwig/oncoact/disruption/ReportableGeneDisruptionFactoryTest.java
> +public class ReportableGeneDisruptionFactoryTest {
What I said for ReportableCNVFactoryTest also applies to this class

2023-08-04 08:59 UTC, KasperWolsink99 commented on common/src/test/java/com/hartwig/oncoact/orange/TestOrangeFactory.java
> +                .worstCodingEffect(PurpleCodingEffect.SPLICE)
Tiny nitpick but worstCodingEffect, adjustedVAF and repeatCount are already set to the desired values by TestPurpleFactory

2023-08-04 08:59 UTC, KasperWolsink99 commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidenceTest.java
> +        ActionableGene deletion = TestServeFactory.geneBuilder().gene("PTEN").event(GeneEvent.DELETION).build();
I would create a new local variable: `String genePten = "PTEN"` to make it more consistent with how it is done for `geneAmp` and `geneDel`

2023-08-04 08:59 UTC, KasperWolsink99 commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/DisruptionEvidenceTest.java
> +            if (evidence.gene().equals(geneToFind)) {
evidence.gene() is marked as @Nullable, so I would do a null check

2023-08-04 08:59 UTC, KasperWolsink99 commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/DisruptionEvidenceTest.java
> +    private static ProtectEvidence find(@NotNull List<ProtectEvidence> evidences, @NotNull String geneToFind) {
```java
        return evidences.stream().filter(x -> Objects.equals(x.gene(), geneToFind))
                .findFirst().orElseThrow(() -> new IllegalStateException("Could not find evidence for gene: " + geneToFind));

```

2023-08-04 08:59 UTC, KasperWolsink99 commented on common/src/main/java/com/hartwig/oncoact/copynumber/ReportableCNVFactory.java
> +                                                     @Nullable Iterable<PurpleGainLoss> germlineLosses) {
I do not think these merge methods are actually needed. In the end this method is only used to concatenate two lists with each other which can be done inline (see https://stackoverflow.com/questions/189559/how-do-i-join-two-lists-in-java).

I don't think the step where we explicitly convert entries to immutables is needed. We need objects of the PurpleGainLoss type which the elements of these iterables already are.

2023-08-04 12:43 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
> +import com.google.common.annotations.VisibleForTesting;
removed

2023-08-04 13:07 UTC, LiekeSchoenmaker commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/DisruptionEvidenceTest.java
> +            if (evidence.gene().equals(geneToFind)) {
yes correct

2023-08-04 13:08 UTC, LiekeSchoenmaker commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/DisruptionEvidenceTest.java
> +    private static ProtectEvidence find(@NotNull List<ProtectEvidence> evidences, @NotNull String geneToFind) {
takes it over, is a nicer solution

2023-08-04 13:51 UTC, LiekeSchoenmaker commented on common/src/test/java/com/hartwig/oncoact/copynumber/ReportableCNVFactoryTest.java
> +public class ReportableCNVFactoryTest {
I was indeed testing if the multiple lists were merging. I have now removed the tests

2023-08-04 13:51 UTC, LiekeSchoenmaker commented on common/src/test/java/com/hartwig/oncoact/disruption/ReportableGeneDisruptionFactoryTest.java
> +public class ReportableGeneDisruptionFactoryTest {
same as ReportableCNVFactoryTest

2023-08-04 13:57 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/copynumber/ReportableCNVFactory.java
> +public class ReportableCNVFactory {
What do you suggest? Now it is merging 2 lists, but this class is mean do every logica which is needed for correct interpretation of the data for medical perspective

2023-08-11 12:57 UTC, mvanniekerkHartwig approved these changes
I can not really judge if the "molecular" parts of the code changes are correct. As far as I can tell everything should work. Just one minor suggestion to avoid repeating yourself.

2023-08-11 13:16 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/copynumber/ReportableCNVFactory.java
> +public final class ReportableCNVFactory {
good point :) I have merged them to one class

2023-08-11 14:22 UTC, merged