Opr 141 rose
hartwigmedical/oncoact pull request #15
Opened 2023-08-10 16:44 UTC by LiekeSchoenmaker

This branch contains the following changes (tickets in jira): 
- OPR-141
- OPR-143
- DEV-3059

2023-08-15 10:32 UTC, KasperWolsink99 requested changes
Looks good, added some comments

2023-08-15 10:32 UTC, KasperWolsink99 commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/PatientReporterApplication.java
> +        report =
I think this functionality belongs in the `AnalysedPatientReport::run` method

2023-08-15 14:49 UTC, LiekeSchoenmaker commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/cfreport/CFReportWriterTest.java
> +        patientReport =
Indeed, I have created a helper method

2023-08-15 14:52 UTC, LiekeSchoenmaker commented on rose/src/test/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgoTest.java
> +        assertEquals(new ArrayList<>(conclusion).get(0), "- HRD (0.8) HRD");
Indeed forgot at some places the ArrayList

2023-08-15 15:04 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/SummaryChapter.java
> +        String sentence = " An overview of all detected oncogenic DNA aberrations can be found in the report.";
what do you exactly mean? I expected that sentence is always added to a new line. Is this not the case follows the code?

2023-08-15 15:08 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +                            && variantMerging.toString().split(", ").length == 1) {
That looks indeed the case, I have updated to the variant list

2023-08-15 15:13 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +            conclusion.add(conclusion.size(), conclusionSentence);
The reason for adding the size of the add function is to add a new item to the last position of the list. Otherwise it is randomly added to the list. There are a couple sentences which should be put on an exact location of the list

2023-08-16 07:31 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +                                conclusion.add(conclusion.size(), "- " + keyMap.getKey() + " (" + variantMerging + ") " + sentence.replace("inactivation", "inactivating mutation") + " "
The reason to replace the string because the same sentence will be used in two conditions. If a variant contains in both alleles (biallelic) in should contains only inactivation. But this sentence should be contains inactivation mutation when the variant is only present in one of the two alleles.

2023-08-16 07:39 UTC, KasperWolsink99 commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/SummaryChapter.java
> +        String sentence = " An overview of all detected oncogenic DNA aberrations can be found in the report.";
Maybe I am mistaken, but `sentence` begins with a whitespace character. So the changes I am proposing would be to change:

`" An overview of all detected oncogenic DNA aberrations can be found in the report."`

to

`"An overview of all detected oncogenic DNA aberrations can be found in the report."`

2023-08-16 09:15 UTC, KasperWolsink99 commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +                                conclusion.add(conclusion.size(), "- " + keyMap.getKey() + " (" + variantMerging + ") " + sentence.replace("inactivation", "inactivating mutation") + " "
Fair enough, I see that you wrote a test case that verifies this behaviour so that is good :)

2023-08-16 12:06 UTC, KasperWolsink99 commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                          if (!keyMap.getValue().iterator().next().biallelic()) {
As discussed privately on teams, I think the `if (!keyMap.getValue().iterator().next().biallelic())` is problematic because it assumes in the conditional that either:

- The set always has exactly one element. If that is the case I think there are more clear ways to write this down.
- The set has some deterministic order. This might be true but we cannot assume this because the `iterator` method says in its javadoc that it returns the elements in "no particular order".
- All entries of the set have the same value for `biallelic`.

I know it is technically not part of the PR but it might be looking into more if we can improve this :)

2023-08-16 14:15 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/PatientReporterApplication.java
> +        report =
done

2023-08-16 14:19 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/SummaryChapter.java
> +        String sentence = " An overview of all detected oncogenic DNA aberrations can be found in the report.";
correct, I have removed the whitespace

2023-08-16 14:47 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +            conclusion.add(conclusion.size(), conclusionSentence);
I see what happened. With a list it is append to the end but with a set it is append randomly. For this reason I leave them as a list without the conclusion.size (isn't needed indeed)

2023-08-17 12:37 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                          if (!keyMap.getValue().iterator().next().biallelic()) {
I analysed the code in details. The set in the map is in this place always length is 1. This is why I pick the first element of the Set. You mention there is a more clearer method for this.  Which method do you want this?

2023-08-17 15:18 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                          if (!keyMap.getValue().iterator().next().biallelic()) {
implemented your suggestion. But is not ideal indeed because it can crash

2023-08-18 10:12 UTC, KasperWolsink99 commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                          if (!keyMap.getValue().iterator().next().biallelic()) {
But wouldn't we want it to crash if `keyMap.getValue().size() != 1`? Because it seems like an illegal state. If the program continues executing while in this illegal state it might lead to inconsistent behaviour and hard to find bugs.  I think in such a scenario crashing the program seems more appropriate. 

Unless I have understood this wrong, but if keyMap.getValue().size() always **must** be 1, then throwing an exception is appropriate if that condition fails to hold in my opinion.

2023-08-18 10:22 UTC, KasperWolsink99 commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +            conclusion.add(conclusion.size(), conclusionSentence);
Yes this is true. Usually sets can be considered unordered: 
`{A, B} == {B, A}` would be considered true

In programming this depends on the specific implementation of the set, but in mathematics usually this proposition holds (that explains the behaviour of the java set)

2023-08-18 10:23 UTC, KasperWolsink99 approved these changes
Approved - please check with @mvanniekerkHartwig if he also wants to take a look at these changes. Also see my remaining comment.

2023-08-18 12:47 UTC, mvanniekerkHartwig requested changes
Update formatting to the oncoact style in all changed files of this PR. Also one super minor comment, otherwise looks good.

2023-08-18 12:47 UTC, mvanniekerkHartwig commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +        if (reportableViruses.size() >= 1) {
`!reportableViruses.isEmpty()`

2023-08-18 14:17 UTC, mvanniekerkHartwig approved these changes

2023-08-18 14:49 UTC, merged