Opr 139 split actionable range
hartwigmedical/oncoact pull request #18
Opened 2023-08-14 15:49 UTC by LiekeSchoenmaker

This PR is related to https://github.com/hartwigmedical/serve/pull/7 which write the output of actionable codon and actionable exon into 2 separate files instead combining into one file. In this PR the 2 new files are used in OncoAct with some new logica. Also, PROTECT is updated to read the file with the treatmentApproaches and codon/exon information.

2023-08-15 08:17 UTC, mvanniekerkHartwig requested changes
Some small stylistic comments

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
> +    @NotNull
Since both these methods are private and static, you can just merge them like:

```java
    @NotNull
    private static KnowledgebaseSource resolveProtectSource(@NotNull ActionableEvent actionable, @Nullable String range,
            @Nullable Integer rangeRank) {
        return ImmutableKnowledgebaseSource.builder()
                .name(actionable.source())
                .sourceEvent(actionable.sourceEvent())
                .sourceUrls(Sets.newTreeSet(actionable.sourceUrls()))
                .evidenceType(determineEvidenceType(actionable, range))
                .rangeRank(rangeRank)
                .evidenceUrls(Sets.newTreeSet(actionable.evidenceUrls()))
                .build();
    }
```

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
>      @NotNull
```java
    @NotNull
    public ImmutableProtectEvidence.Builder evidenceBuilder(@NotNull ActionableEvent actionable) {
        return evidenceBuilderRange(actionable, null, null);
    }
```

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
> +            if (range != null) {
Better to leave in separate method, `fromActionableRange`

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
> +            if (range != null) {
Also you can get rid of the null check if you switch to using `Objects.equals`:

```java
    @NotNull
    private static EvidenceType fromActionableRange(final @NotNull ActionableEvent actionable, final @Nullable String range) {
        if (Objects.equals(range, "codon")) {
            return EvidenceType.CODON_MUTATION;
        } else if (Objects.equals(range, "exon")) {
            return EvidenceType.EXON_MUTATION;
        } else {
            throw new IllegalStateException("Unexpected actionable event detected in variant evidence: " + actionable);
        }
    }
```

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
> +            if (range != null) {
Also consider adding the `range` to the `IllegalStateException` to ease debugging.

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
> +                if (range.equals("codon")) {
Switch to `Objects.equals` and get rid of the null check (here and everywhere else). In general using `Objects.equals` is a nice way to avoid checking for null.

2023-08-15 08:17 UTC, mvanniekerkHartwig commented on protect/src/main/java/com/hartwig/oncoact/protect/serve/ServeOutput.java
> +    public static ActionableEvents loadServeData(@NotNull ProtectConfig config, @NotNull OrangeRefGenomeVersion refGenomeVersion) throws IOException {
formatting

2023-08-15 11:18 UTC, LiekeSchoenmaker commented on pom.xml
> +        <serve.version>local-SNAPSHOT</serve.version>
We should release also a new serve version. For now I have update them to 2.0.1

2023-08-15 11:22 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/serve/ServeOutput.java
> +    public static ActionableEvents loadServeData(@NotNull ProtectConfig config, @NotNull OrangeRefGenomeVersion refGenomeVersion) throws IOException {
done

2023-08-15 11:31 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
> +                if (range.equals("codon")) {
Good to know, for future I will use the Object.equals instead the above if function

2023-08-15 11:41 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
> +            if (range != null) {
updated with your feedback

2023-08-15 14:56 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/PersonalizedEvidenceFactory.java
> +    @NotNull
correct, because rangeRank could be null only in range function this Integer contains data

2023-08-16 08:13 UTC, mvanniekerkHartwig approved these changes

2023-08-21 11:28 UTC, merged