Medical updates v1
hartwigmedical/oncoact pull request #21
Opened 2023-08-28 16:03 UTC by LiekeSchoenmaker

Scope: 
- Fix bug of displaying variant in report
- Solves different feedback of medical team 
- Fix bug of clinical transcript for ROSE/PROTECT

Release of orange datamodel should be made (29 AUG)

2023-08-29 14:40 UTC, KasperWolsink99 requested changes
Good changes! I left some comments.

2023-08-29 14:40 UTC, KasperWolsink99 commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
>          } else {
This code can be improved. The problem is that it is possible for the `variant` variable to be an instance of a class other than `ReportableVariant` or `PurpleVariant`. In this case, the cast statements will fail and the code will throw a `ClassCastException` error.


I would make the following changes:

if (variant instanceof ReportableVariant) {
ReportableVariant reportable = (ReportableVariant) variant;
effect = reportable.canonicalCodingEffect();
} else if (variant instanceof PurpleVariant) {
PurpleVariant purple = (PurpleVariant) variant;
effect = purple.canonicalImpact().codingEffect();
} else {
// do something else, ie throw an IllegalArgumentException
}

these changes will make the code more type safe and less error-prone in the future.

2023-08-30 07:14 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/protect/EventGenerator.java
> +            if (clinical != null) {
Indeed, I have update them

2023-08-30 07:15 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctions.java
> +                    if (evidenceType.equals("treatmentApproach")) {
you are right 👍

2023-08-30 07:18 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/SummaryChapter.java
> +        reportDocument.add(div.setFixedPosition(leftPosition, 70, width));
solved, I append a variable for the bottom position

2023-08-30 07:23 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailChapter.java
> +        reportDocument.add(new Paragraph("\nThe information regarding 'primary tumor location', 'primary tumor type' and 'biopsy location'"
I added a empty paragraph instead the newline character with a comment. We want some space between both elements for readability in the PDF

2023-08-30 07:27 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/components/SidePanel.java
> +        int height;
👍

2023-08-30 07:28 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/components/SidePanel.java
>              if (isPrimaryTumor != null) {
You are right, this if statement is already done above and make them "-" when nullable

2023-08-30 07:29 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/components/SidePanel.java
> +                cv.add(createSidePanelDiv(++sideTextIndex, "Biopsy from primary tumor", String.valueOf(isPrimaryTumor)));
👍

2023-08-30 07:30 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/components/SidePanel.java
> +    private static void renderBackgroundRect(boolean fullHeight, @NotNull PdfCanvas canvas, @NotNull Rectangle pageSize,
done

2023-08-30 07:33 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/components/SidePanel.java
> +            String isPrimaryTumor = "-";
It is indeed not more a boolean because we want a "-" when this is nullable. However I will leave this name because this detemined if the biopsy is taken from the primary tumor or not. Sometimes this is unknown but the value should be otherwise true/false

2023-08-30 07:36 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/SomaticVariants.java
> +        } else {
This is the smaller version with the same functionality. Refactor to the small version

2023-08-30 07:39 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/SomaticVariants.java
>          // TODO Check whether evaluation still works
I have them removed. This TODO is from december 2022 and look to the PAVE readme and this looks correct to me

2023-08-30 07:41 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/ReportResources.java
> +            // Width of the content on a narrow page (page without full side panel)
This due the formatting of the schema

2023-08-30 08:08 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
>          } else {
In theory/practice every variant is present in the instance of PurpleVariant and only the variants which has the flag reported from purple those are as wel in the instanve ReportabelVariant. But for error-prone I have added the IllegalArgumentException

2023-08-30 08:28 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/protect/EventGenerator.java
> +    public static StringBuilder determineVariantAnnotations(@NotNull String hgvsCoding, @NotNull String hgvsProtein,
I made a mistake, and take the wrong arguments. I have update them

2023-08-30 10:21 UTC, KasperWolsink99 commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailChapter.java
> +        reportDocument.add(new Paragraph("\nThe information regarding 'primary tumor location', 'primary tumor type' and 'biopsy location'"
I did a small investigation and have found `Paragraph#setMarginBottom` ([docs](https://api.itextpdf.com/iText/java/7.2.4/com/itextpdf/layout/element/BlockElement.html#setMarginBottom-float-:~:text=public%C2%A0T%C2%A0setMarginBottom(float%C2%A0value))) which accepts a float and adds whitespace to the bottom of the paragraph. This might is what you need.

2023-08-30 10:26 UTC, KasperWolsink99 requested changes
Nice changes! I left one comment unresolved with a small improvement idea

2023-08-30 10:41 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailChapter.java
> +        reportDocument.add(new Paragraph("\nThe information regarding 'primary tumor location', 'primary tumor type' and 'biopsy location'"
indeed a nice libary. Have solved it with setMarginTop

2023-08-30 10:41 UTC, KasperWolsink99 approved these changes
Approved, maybe ask @mvanniekerkHartwig if he still wants to take a look

2023-08-30 11:16 UTC, mvanniekerkHartwig commented on common/src/main/java/com/hartwig/oncoact/protect/EventGenerator.java
> +        if (hgvsProtein != null && !hgvsProtein.isEmpty() && !hgvsProtein.equals("p.?")) {
Use `!Strings.isNullOrEmpty(hgvsProtein)` in both if statements

2023-08-30 11:56 UTC, mvanniekerkHartwig requested changes
Some minor style and code clarity comments.

2023-08-30 11:56 UTC, mvanniekerkHartwig commented on common/src/main/java/com/hartwig/oncoact/protect/EventGenerator.java
> +        if (hgvsProtein != null && !hgvsProtein.isEmpty() && !hgvsProtein.equals("p.?")) {
Use `!Strings.isNullOrEmpty(hgvsProtein)` in both if statements

2023-08-30 11:56 UTC, mvanniekerkHartwig commented on common/src/main/java/com/hartwig/oncoact/protect/EventGenerator.java
> +    @Nullable
I refactored `determineVariantAnnotationClinical`, `variantEvent`, and `canonicalVariantEvent` to clear up the logic a little bit. I recommend changing these methods for my refactored version (the actual logic should be identical):

```java
    @NotNull
    public static String variantEvent(@NotNull Variant variant) {
        if (variant instanceof ReportableVariant) {
            return reportableVariant((ReportableVariant) variant);
        } else if (variant instanceof PurpleVariant) {
            PurpleTranscriptImpact purpleTranscriptImpact = ((PurpleVariant) variant).canonicalImpact();
            return determineVariantAnnotationClinical(purpleTranscriptImpact);
        } else {
            throw new IllegalArgumentException(String.format("Unexpected variant type. Variant was: %s", variant));
        }
    }

    @NotNull
    private static String reportableVariant(final ReportableVariant variant) {
        String variantEvent = determineVariantAnnotation(variant.canonicalHgvsCodingImpact(),
                    variant.canonicalHgvsProteinImpact(),
                    variant.canonicalEffect(),
                    variant.canonicalCodingEffect());
        PurpleTranscriptImpact otherImpactClinical = variant.otherImpactClinical();
        if (otherImpactClinical == null) {
            return variantEvent;
        }
        String clinical = determineVariantAnnotationClinical(otherImpactClinical);
        if (variantEvent.equals(clinical)) {
            return variantEvent;
        }
        return variantEvent + " (" + clinical + ")";
    }

    @NotNull
    private static String determineVariantAnnotationClinical(@NotNull PurpleTranscriptImpact purpleTranscriptImpact) {
        return determineVariantAnnotation(purpleTranscriptImpact.hgvsCodingImpact(), purpleTranscriptImpact.hgvsProteinImpact(),
                concat(purpleTranscriptImpact.effects()),
                purpleTranscriptImpact.codingEffect());
    }
```

2023-08-30 11:56 UTC, mvanniekerkHartwig commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariantFactory.java
> +            Sets.newHashSet(PurpleDriverType.MUTATION, PurpleDriverType.GERMLINE_MUTATION);
Use `Set.of` so you use an `UnmodifiableSet`.

2023-08-30 11:56 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/ReportResources.java
> +            // Width of the content on a narrow page (page without full side panel)
Move the comments above the lines like so:
```java
    // Width of the content on a narrow page (page with full side panel)
    public static final float CONTENT_WIDTH_NARROW = 330;
    // Width of the content on a narrow page (page without full side panel)
    public static final float CONTENT_WIDTH_WIDE = 510;
    // Width of the content on a narrow page (page with full side panel)
    public static final float CONTENT_WIDTH_WIDE_SMALL = 240;
    // Width of the content on a narrow page (page without full side panel)
    public static final float CONTENT_WIDTH_WIDE_SUMMARY_LEFT = 320;
    // Width of the content on a narrow page (page without full side panel)
    public static final float CONTENT_WIDTH_WIDE_SUMMARY_RIGHT = 170;
```

2023-08-30 13:51 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/protect/EventGenerator.java
> +        if (hgvsProtein != null && !hgvsProtein.isEmpty() && !hgvsProtein.equals("p.?")) {
👍

2023-08-30 13:52 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariantFactory.java
> +            Sets.newHashSet(PurpleDriverType.MUTATION, PurpleDriverType.GERMLINE_MUTATION);
changed

2023-08-30 13:53 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/ReportResources.java
> +            // Width of the content on a narrow page (page without full side panel)
done

2023-08-30 14:06 UTC, mvanniekerkHartwig approved these changes

2023-08-30 14:07 UTC, merged