Medical updates v2
hartwigmedical/oncoact pull request #23
Opened 2023-09-06 14:51 UTC by LiekeSchoenmaker

Different updates requestered from medical team

2023-09-06 15:01 UTC, mvanniekerkHartwig reviewed
Looks good, I only have one question and one suggestion.

2023-09-06 15:01 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +                LOGGER.warn("None requester name of report is known. Solve before reporting!");
Same here.

2023-09-06 15:14 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +                LOGGER.warn("None requester name of report is known. Solve before reporting!");
both are fine I think. But have implement a try/catch function.

2023-09-06 15:23 UTC, mvanniekerkHartwig requested changes

2023-09-06 15:23 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +            } catch (NullPointerException exception) {
This last change makes no sense, there is nothing to catch here. I'd rather you revert this change.
I meant you could change the code to something like:
```java
            if (studyPI != null) {
                requesterNameReport = studyPI;
            } else {
                throw new IllegalArgumentException("None requester name of report is known. Solve before reporting!");
            }
```

But only if you're ok with stopping a patient reporter run prematurely on missing this information (which I think is probably justified if it needs to be fixed before reporting anyway).

2023-09-07 07:07 UTC, mvanniekerkHartwig approved these changes

2023-09-07 07:09 UTC, merged