Lama datamodel
hartwigmedical/oncoact pull request #3
Opened 2023-06-02 15:10 UTC by LiekeSchoenmaker

2023-06-14 13:42 UTC, mvanniekerkHartwig requested changes
Great changes overall. I had some minor comments, most of them related to code cleanup and nullability of lama fields.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReport.java
> +    public abstract PatientReporterData patientReporterData();
rename to `lamaPatientData` everywhere.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        GenomicAnalysis genomicAnalysis = genomicAnalyzer.run(orange, reportableEvidence, true);
Always true, replace with constant (and also remove the parameter in `determineNotify` and `notifyGermlineVariant`)

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        GenomicAnalysis filteredAnalysis = ConsentFilterFunctions.filter(genomicAnalysis, true);
Always true, replace with constant (and also remove the parameter in `filterVariants` and `filterEvidenceForGermlineConsent`)

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        LOGGER.info(" Primary tumor details: {}{}", report.patientReporterData().getPrimaryTumorType().getLocation(), !report.patientReporterData().getPrimaryTumorType().getLocation().isEmpty() ? " (
Line is too long. Also probably doesn't make sense to print is the location is empty. Replace with something like:
```java
        TumorType primaryTumorType = report.lamaPatientData().getPrimaryTumorType();
        if (!primaryTumorType.getLocation().isEmpty()) {
            LOGGER.info(" Primary tumor details: {} ({})", primaryTumorType.getLocation(), primaryTumorType.getType());
        }
```

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        LocalDate tumorArrivalDate = report.patientReporterData().getTumorArrivalDate();
Instead of repeating `report.patientReporterData()`, set the variable once: `var lamaPatientData = report. patientReporterData();`

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceOffLabelChapter.java
> +        boolean flagGermline = report.patientReporterData().getReportSettings().getFlagGermlineOnReport() != null ? report.patientReporterData().getReportSettings().getFlagGermlineOnReport() : false;
`boolean flagGermline = Objects.requireNonNullElse(report.lamaPatientData().getReportSettings().getFlagGermlineOnReport(), false);`
Also check if this variable can actually be null. Probably it's never null, but it's just a faulty nullable annotation.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceOnLabelChapter.java
> +        boolean flagGermline = report.patientReporterData().getReportSettings().getFlagGermlineOnReport() != null ? report.patientReporterData().getReportSettings().getFlagGermlineOnReport() : false;
boolean flagGermline = Objects.requireNonNullElse(report.lamaPatientData().getReportSettings().getFlagGermlineOnReport(), false);
Also check if this variable can actually be null. Probably it's never null, but it's just a faulty nullable annotation.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceOnLabelChapter.java
> +        boolean flagGermline = report.patientReporterData().getReportSettings().getFlagGermlineOnReport() != null ? report.patientReporterData().getReportSettings().getFlagGermlineOnReport() : false;
boolean flagGermline = Objects.requireNonNullElse(report.lamaPatientData().getReportSettings().getFlagGermlineOnReport(), false);
Also check if this variable can actually be null. Probably it's never null, but it's just a faulty nullable annotation.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/DetailsAndDisclaimerChapter.java
> +        if (reportingId.substring(0, 4).matches("[a-zA-Z]+")) {
I don't really like this very implicit check. We should add a `isStudy` field to the LAMA response.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/GenomicAlterationsChapter.java
> -                TableUtil.createReportContentTable(new float[] { 90, 95, 50 }, new Cell[] {}, ReportResources.CONTENT_WIDTH_WIDE_SMALL);
Looks like we are using a different formatter from the one that was used to write this file.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailDisclaimerChapter.java
> +        assert pathologyId != null;
Get rid of this assert.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailDisclaimerChapter.java
> +            assert purity != null;
Get rid of this assert.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailDisclaimerChapter.java
> +        assert effectivePurity != null;
Get rid of this assert.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/panel/SampleAndDisclaimerChapter.java
> +        if (reportingId.substring(0, 4).matches("[a-zA-Z]+")) {
Same here, we should include a `isStudy` field to the LAMA response.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +    public static InterpretTumorType interpretTumorType(@Nullable TumorType tumorType) {
You can avoid this method and the `InterpretTumorType` class if you change `TumorLocationAndTypeTable::createTumorLocation` to:

```java
    @NotNull
    public static Table createTumorLocation(@Nullable TumorType tumorType, float width) {
        Table table = new Table(UnitValue.createPercentArray(new float[] { 2, 2 }));
        table.setWidth(width);

        table.addCell(TableUtil.createLayoutCell().add(new Paragraph("PRIMARY TUMOR LOCATION").addStyle(ReportResources.subTextStyle())));
        table.addCell(TableUtil.createLayoutCell().add(new Paragraph("PRIMARY TUMOR TYPE").addStyle(ReportResources.subTextStyle())));

        String tumorLocation = Optional.ofNullable(tumorType).map(TumorType::getLocation).orElse("");
        table.addCell(TableUtil.createLayoutCell().add(DataLabel.createDataLabel(tumorLocation)));
        String type = Optional.ofNullable(tumorType).map(TumorType::getType).orElse("");
        table.addCell(TableUtil.createLayoutCell().add(DataLabel.createDataLabel(type)));

        return table;
    }
```

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +            if (sampleDate == null) {
Formatting, and I think `sampleDate` is never null.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +        if (hospital != null) {
Also those fields will never be null.

2023-06-14 13:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/qcfail/QCFailReport.java
> +    public abstract PatientReporterData patientReporterData();
Rename

2023-06-15 07:42 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        LOGGER.info(" Primary tumor details: {}{}", report.patientReporterData().getPrimaryTumorType().getLocation(), !report.patientReporterData().getPrimaryTumorType().getLocation().isEmpty() ? " (
Better (because type can be null):
```java
        TumorType primaryTumorType = lamaPatientData.getPrimaryTumorType();
        if (primaryTumorType != null) {
            LOGGER.info(" Primary tumor details: {} ({})", primaryTumorType.getLocation(), primaryTumorType.getType());
        }
```

2023-06-15 08:03 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +    public static String extractEarliestArrivalDate(@Nullable LocalDate refDate, @Nullable LocalDate sampleDate){
Change this method to take `lamaPatientData`

2023-06-15 08:04 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +    public static String hospitalContactReport(@Nullable String studyPI, @Nullable String requester, @Nullable String hospital,
Change this method to take lamaPatientData

2023-06-16 08:21 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/OutputFileUtil.java
>  public final class OutputFileUtil {
File names updates. But the names will be discuss with medical team

2023-06-16 08:22 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/PatientReporterApplication.java
> +        LOGGER.info("Display tag name of this sample is: {}", report.patientReporterData().getCohort());
Is not more relevant because no filtering will be done on cohort level. So is removed

2023-06-16 08:22 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/panel/SampleAndDisclaimerChapter.java
> +        if (reportingId.substring(0, 4).matches("[a-zA-Z]+")) {
used the isStudy field from LAMA

2023-06-16 08:23 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +            if (sampleDate == null) {
sampleDate is optional at the point of registration, so could be nullable

2023-06-16 08:29 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        GenomicAnalysis genomicAnalysis = genomicAnalyzer.run(orange, reportableEvidence, true);
used the lamapPatient report setting germline flag (is currently always false). The filtering of `determineNotify` and `notifyGermlineVariant` is needed when the flag is true

2023-06-16 08:32 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceOffLabelChapter.java
> +        boolean flagGermline = report.patientReporterData().getReportSettings().getFlagGermlineOnReport() != null ? report.patientReporterData().getReportSettings().getFlagGermlineOnReport() : false;
removes, assume your lama changes will be accepted

2023-06-16 08:33 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceOnLabelChapter.java
> +        boolean flagGermline = report.patientReporterData().getReportSettings().getFlagGermlineOnReport() != null ? report.patientReporterData().getReportSettings().getFlagGermlineOnReport() : false;
updated, assume your lama changes will be accepted

2023-06-16 08:33 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceOnLabelChapter.java
> +        boolean flagGermline = report.patientReporterData().getReportSettings().getFlagGermlineOnReport() != null ? report.patientReporterData().getReportSettings().getFlagGermlineOnReport() : false;
updated, assume your lama changes will be accepted

2023-06-16 08:34 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/GenomicAlterationsChapter.java
> -                TableUtil.createReportContentTable(new float[] { 90, 95, 50 }, new Cell[] {}, ReportResources.CONTENT_WIDTH_WIDE_SMALL);
what do you mean?

2023-06-16 08:57 UTC, mvanniekerkHartwig requested changes
Great improvements overall. I had some more comments for the second round.

2023-06-16 08:57 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +        GenomicAnalysis genomicAnalysis = genomicAnalyzer.run(orange, reportableEvidence, reportData.lamaPatientData().getReportSettings().getFlagGermlineOnReport());
Extract `reportData.lamaPatientData().getReportSettings().getFlagGermlineOnReport()` to variable.

2023-06-16 08:57 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +                LOGGER.info(" Primary tumor details: {}", primaryTumorType.getLocation());
It's not really a disaster if we print `()` if type is an empty string. So I think we should just get rid of this case.

2023-06-16 08:57 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailDisclaimerChapter.java
> +            String pathologyId = failReport.lamaPatientData().getPathologyNumber();
Extract `failReport.lamaPatientData().getPathologyNumber()` to a variable. Then the assert is no longer necessary.

2023-06-16 08:57 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/failed/QCFailDisclaimerChapter.java
> +        if (failReport.lamaPatientData().getShallowPurity() != null) {
Extract `failReport.lamaPatientData().getShallowPurity()` to a variable.

2023-06-16 08:57 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/components/SidePanel.java
> +        if (lamaPatientData.getReportingId().substring(0, 4).matches("[a-zA-Z]+")) {
Use isStudy instead.

2023-06-23 08:41 UTC, mvanniekerkHartwig requested changes
Just some super small comments left. Looks really nice!

2023-06-23 08:41 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/ConsentFilterFunctions.java
> +            @NotNull Boolean germlineReportingLevel) {
Rename to `boolean flagGermline` everywhere in this class (`@NotNull` is then no longer necessary).

2023-06-23 08:41 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/GenomicAnalyzer.java
> +                               @NotNull Boolean germlineReportingLevel) {
Rename to `boolean flagGermline` everywhere in this class

2023-06-23 08:41 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +public class LamaInterpretation {
make the class `final`.

2023-06-23 08:41 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/lama/LamaInterpretation.java
> +    public static String hospitalContactReport(@Nullable PatientReporterData lamaPatientData) {
Should be `@NotNull`

2023-06-23 12:14 UTC, mvanniekerkHartwig approved these changes

2023-06-23 14:12 UTC, merged