Silo datamodel
hartwigmedical/oncoact pull request #4
Opened 2023-06-26 11:36 UTC by LiekeSchoenmaker

2023-06-26 13:00 UTC, mvanniekerkHartwig requested changes
Some small comments

2023-06-26 13:03 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/diagnosticsilo/DiagnosticSiloJsonInterpretation.java
> +    public static String determineName(@NotNull PatientInformationResponse patientInformationData) {
I guess my code doesn't really work because it inserts too many spaces :) anyway, maybe you can extract something useful out of it.

2023-06-26 13:33 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/PanelReporterConfig.java
> +        options.addOption(IS_DIAGNOSTIC, false, "If provided, use diagnostic patient data ");
I think this is needed becuase this is the place for making the values optional dus the false flag

2023-06-26 14:02 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/PanelReporterConfig.java
> +        options.addOption(IS_DIAGNOSTIC, false, "If provided, use diagnostic patient data ");
Ah I see, my mistake. It stands for `hasArg`, docstring: "flag signally if an argument is required after this option".
So I think that `DIAGNOSTIC_SILO_JSON` should be set to `true`, but this can can stay `false`. Same for `PatientReporterConfig`.

2023-06-27 10:37 UTC, mvanniekerkHartwig approved these changes

2023-06-27 10:47 UTC, merged