Opr 151 germline tumor first approach
hartwigmedical/oncoact pull request #40
Opened 2024-01-30 09:06 UTC by LiekeSchoenmaker

Support the pure germline findings in OncoAct rapportage

2024-01-30 12:59 UTC, mvanniekerkHartwig commented
I'll review when we have an orange-datamodel version that can actually compile the code :)

2024-01-30 15:44 UTC, DFKoetsier requested changes
I wasn't always sure about what behaviour was intended, so feel free to ignore comments if the code is implemented as intended.

I did also find a few things that should probably be changed, but nothing major.

2024-01-30 15:44 UTC, DFKoetsier commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/SomaticVariants.java
>              double flooredCopyNumber = Math.max(0, totalCopyNumber);
This method isn't actually Nullable

2024-01-30 15:44 UTC, DFKoetsier commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidence.java
>          }
The list in the for loop might look better in the form of a local variable

2024-01-30 15:44 UTC, DFKoetsier commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidence.java
>          }
Shouldn't allGermlineLossOfHeterozygosities be included here? Or would that introduce too many false positives or something?

2024-01-30 15:44 UTC, DFKoetsier commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
Again, I would prefer something like `convertedGermlineLossOfHeterozygosities` over `germlineLossOfHeterozygosityConversion`.

2024-01-30 15:44 UTC, DFKoetsier commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                      actionable.add("virus");
The code here checks that condition is ALWAYS, but just above this all viruses with driver likelihood LOW are ignored. 

I think the check on the driver likelihood should be removed above, and the condition in this if statement should be replaced by `entry==null || (entry.condition() == Condition.HIGH_ONLY && virus.virusDriverLikelihoodType() != VirusLikelihoodType.HIGH)`

And a similar change should probably be implemented for the two other if statements below that have to do with entry.condition().

2024-01-31 15:50 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/GenomicAlterationsChapter.java
>              contentTable.addCell(tableUtil.createContentCell(gainLoss.gene()));
point 1; I will discuss tomorrow with Paul. My assumption is full/partial gene but let wait on his opinion

point 2; this would not populate to the clinical evidence. But the full gene should end for example as deletion

2024-01-31 15:51 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidence.java
> +                        || reportable.interpretation() == CopyNumberInterpretation.FULL_GENE;
correct, I have update it

2024-01-31 15:58 UTC, LiekeSchoenmaker commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/ExampleAnalysisTestFactory.java
>          List<GeneDisruption> disruptions = createCOLO829Disruptions();
indeed forgot the germline only variants in the test

2024-01-31 16:13 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ExplanationChapter.java
>          table.addCell(TableUtil.createLayoutCell());
I overlooked it. I have updated where relevant

2024-01-31 16:16 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/SomaticVariants.java
>              double flooredCopyNumber = Math.max(0, totalCopyNumber);
updated to the annotation @Notnull

2024-01-31 16:18 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidence.java
>          }
done

2024-01-31 16:22 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidence.java
>          }
I has not detected the object allGermlineLossOfHeterozygosities. But have now include them. But maybe this arise many false positives. But I will discuss it tomorrow also

2024-01-31 16:23 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
done

2024-01-31 16:28 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                      actionable.add("virus");
First I have updated the condition in the ROSE database. But I have leave the first check on driverLikelihood, so this check is executed ones.

2024-01-31 16:41 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariantSource.java
> +    GERMLINE_ONLY
You are right.......This was not implemented in all the tools and forgot it at the filter/curation classes

2024-01-31 16:51 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariantFactory.java
I am not sure. But update the code with your suggestion. I should verify the results if this is something we want!

2024-01-31 16:59 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/GeneUtil.java
>          if (!hasReliablePurity) {
I have split them into 2 methods. The strings.Empty was implemented for the GERMLINE_VARIANTS for eg. hospot/biallelic enz.

2024-02-01 16:07 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/SomaticVariants.java
updated the code for a correct sortering. Maybe good to review If I didn't take a mistake. But the approach is as follows: 
- first create a map on gene level 
- sort the list per gene 
- for the map on highest driverlikelihood per gene

2024-02-02 14:30 UTC, DFKoetsier requested changes
The changes look good! I do have a few more remarks

2024-02-02 14:35 UTC, DFKoetsier commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                      actionable.add("virus");
After discussing this with Lieke, I think the current implementation is good enough

2024-02-05 08:55 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
>                      actionable.add("virus");
Indeed, I have created a new ticket to improve the ConclusionAlgo logica

2024-02-05 09:03 UTC, LiekeSchoenmaker commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/ExampleAnalysisTestFactory.java
>      }
updated. However, the code does the same

2024-02-05 09:12 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/copynumber/ReportablePurpleGainLoss.java
> +    }
In my opinion we should do this in the for loop. The logics does the same

2024-02-05 09:17 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/copynumber/CopyNumberInterpretation.java
> +}
This is still needed because you shouls 2 different enums geneProportion (FULL_GENE & PARTIAL_GENE) & CopyNumberInterpretation (FULL_GAIN & PARTIAL_GAIN & FULL_LOSS & PARTIAL_LOSS ) merge to one enum

2024-02-05 11:35 UTC, mvanniekerkHartwig requested changes
Looking good! I had a bunch of smallish comments which I could all resolve very easily. To make it a bit easier I already applied my changes and pushed a branch as a PR. If you agree with my changes you can merge them into your branch.
See: https://github.com/hartwigmedical/oncoact/pull/41

2024-02-05 11:35 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/data/SomaticVariants.java
> +        Map<String, List<ReportableVariant>> geneToReportableVariants = Maps.newHashMap();
I prefer this one-liner:
```java
return variants.stream().collect(Collectors.groupingBy(ReportableVariant::gene, Collectors.toList()));
```

2024-02-05 15:21 UTC, mvanniekerkHartwig requested changes
Only one tiny comment left :)

2024-02-05 15:21 UTC, mvanniekerkHartwig commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariantFactory.java
> +        Set<ReportableVariant> result = Sets.newHashSet();
Just this one.

2024-02-05 15:49 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariantFactory.java
> +        Set<ReportableVariant> result = Sets.newHashSet();
I have revert it. This doesn't combine the 2 lists

2024-02-05 15:54 UTC, mvanniekerkHartwig approved these changes

2024-02-05 19:24 UTC, DFKoetsier approved these changes
The changes look great.
I do have a few more remarks, but nothing major. I think the one in VariantEvidence should probably be fixed, but I'm not fully sure it could actually be a problem. For the other ones, I'd also be fine with merging as is without further changes. I'm therefore approving the pull request

2024-02-05 19:24 UTC, DFKoetsier commented on common/src/main/java/com/hartwig/oncoact/util/ListUtil.java
>  import org.jetbrains.annotations.Nullable;
These imports aren't used anymore.

2024-02-06 08:39 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
>              isCanonical = reportable.isCanonical();
null is now also a option for variants for germline only variants. I have updated them to handle laso the nullable value

2024-02-15 10:30 UTC, merged