INFRA-453: Port ONCOACT to ORANGE datamodel 2.3.0
hartwigmedical/oncoact pull request #42
Opened 2024-05-02 20:44 UTC by kzuberihmf

* Updates dependency on orange-datamodel from 1.3.3 to 2.3.0
* Various updates to reflect changes to datamodel attributes: HomozygousDisruption -> LinxHomozygousDisruption, etc 
* Updated orange.json files in test resources to use version from hmftools/orange-datamodel

A few notes:
* LinxFusion.display() now formats fusions as "geneStart::geneEnd", small formatting change that can show up in output
* The model no longer has PurpleFit methods hasSufficientQuality() and containsTumorCells(). These are now determined from PurpleFit, implemented in a helper class in oncoact/common
* There is some refactoring implied in the existing code for ReportableVariant/PurpleVariant which previously shared a Variant interface that has been removed. To expedite the update I duplicated (!!) code in protect/evidence/VariantEvidence. However this should be properly refactored, I suspect there's a plan somewhere for how this should be organized but didn't find it in Jira and not sure what it is.

So apart from the VariantEvidence cleanup remaining for the future, the code is ported and unit tests pass. Hope that's enough to move forward for now. Validation testing on proper data of course should be done.

2024-05-03 00:36 UTC, kzuberihmf commented
Also, just in case its relevant, note that orange-datamodel has had a further small update since 2.3.0 (reported flag on transcript). It just needs to have a release made along with the corresponding version of Orange.

2024-05-03 07:05 UTC, mvanniekerkHartwig approved these changes
Looks good afaict, I will wait for David/Lieke to take a better look at the "genomic" side of the changes.

2024-05-03 15:09 UTC, DFKoetsier requested changes
Only the isUpstream method needs to be fixed. Other than that it looks great!

2024-05-06 16:46 UTC, kzuberihmf commented on common/src/main/java/com/hartwig/oncoact/disruption/GeneDisruptionFactory.java
> +        return breakend.geneOrientation().equals(BREAKEND_ORIENTATION_UPSTREAM);
Thank-you for carefully checking and the detailed explanation! This was also passing silently, so added a test, hope I've interpreted it correctly now.

2024-05-06 16:48 UTC, kzuberihmf commented on common/src/test/resources/orange/minimally.populated.orange.json
> +          "reported": true
Yes I grabbed the latest version figuring it was compatible. If that's ok I'll leave it.

2024-05-07 10:42 UTC, DFKoetsier approved these changes
Looks great!

2024-05-07 13:30 UTC, kzuberihmf commented
I don't seem to be able to create an issue on the OPS Jira board for refactoring the ReportableVariant/PurpleVariant related duplication, that's something someone might want to pick up when there's time. Merging this now, & thanks.

2024-05-07 13:31 UTC, merged