Implementation of the support for CKB trials
hartwigmedical/oncoact pull request #43
Opened 2024-05-28 11:35 UTC by LiekeSchoenmaker

SCOPE: 
- Solve INC-397 select highest evidence based on level and direction 
- Update TMB cutoff from 16 to 10
- Support the new serve data model (master branch of https://github.com/hartwigmedical/serve) 
- Update new data model of protect + loading into the database
- Add logica to support only NL clinical studies
- Add filter on gender of study 
- Sort ROSE output on alphabetically order 
- Update layout of the clinical evidence section of the rapportage 
- Update disclaimers of the patient reporter

2024-06-03 09:36 UTC, mdenburger requested changes

2024-06-03 09:36 UTC, mdenburger commented on common/src/main/java/com/hartwig/oncoact/protect/ProtectEvidenceFile.java
> +    private static String therapyName(@Nullable ClinicalTrial clinicalTrial, @Nullable Treatment treatment) {
The exact same method exists in `ProtectDAO.java`. Move to some common utility class and reuse the same method in both places?

2024-06-03 09:36 UTC, mdenburger commented on common/src/main/java/com/hartwig/oncoact/protect/ProtectEvidenceFile.java
> +            throw new IllegalStateException("An actionable event cannot be both a treatment and clinical trial");
I'd log some details of the clinical trail and treatment here, so you can locate them sooner whenever this strange event happens

2024-06-03 09:36 UTC, mdenburger commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctionsTest.java
> +    public List<ProtectEvidence> createProtectEvidenceList(@NotNull EvidenceLevel level, @NotNull EvidenceDirection direction) {
Can be `private`

2024-06-03 09:36 UTC, mdenburger commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctionsTest.java
> +        evidences.add(createProtectEvidence(level, direction));
Can be simplified to `return Collections.singletonList(createProtectEvidence(level, direction))`. 

Whenever you need a list, set or map with only one item, use the `Collections.singletonXXX` methods: they're faster, simpler and cheaper to use and return an immutable collection.

2024-06-03 09:36 UTC, mdenburger commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/ExampleAnalysisTestFactory.java
> +                        .treatmentApproachesTherapy(Sets.newHashSet())
Use `Collections.emptySet()` whenever you need an empty set. That's cheaper to create an always immutable. Same for lists and maps.

2024-06-03 09:36 UTC, mdenburger commented on protect/src/main/java/com/hartwig/oncoact/protect/algo/EvidenceKey.java
>                  evidence.treatment().name(),
According to the annotations, `treatment()` can be `null`. Something to account for here?

2024-06-03 09:36 UTC, mdenburger commented on protect/src/main/java/com/hartwig/oncoact/protect/algo/ProtectAlgo.java
> +        return updatedForTrials;
No blacklist needed anymore for CKB?

2024-06-03 09:36 UTC, mdenburger commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/CopyNumberEvidence.java
> +                    if (Genes.MSI_GENES.contains(actionable.gene())) {
Can be simplified to `report = Genes.MSI_GENES.contains(actionable.gene())`

2024-06-03 09:36 UTC, mdenburger commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
> +                    if (Genes.MSI_GENES.contains(gene.gene())) {
Can be simplified to `report = Genes.MSI_GENES.contains(gene.gene())`

2024-06-03 09:36 UTC, mdenburger commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
>                  .eventIsHighDriver(driverInterpretation == null ? null : EvidenceDriverLikelihood.interpretVariant(driverInterpretation))
"reported" is no longer needed? It still exists in the builder.

2024-06-03 09:36 UTC, mdenburger commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/VirusEvidenceTest.java
> +        ;
Spurious comma? :)

2024-06-05 10:48 UTC, LiekeSchoenmaker commented on rose/README.md
> +determined by the
updated

2024-06-05 10:49 UTC, LiekeSchoenmaker commented on rose/src/main/java/com/hartwig/oncoact/rose/conclusion/ConclusionAlgo.java
> +import com.hartwig.oncoact.rose.actionability.*;
Have solved the problem already

2024-06-05 10:50 UTC, LiekeSchoenmaker commented on pom.xml
> +        <serve.version>4.0.1-beta.1</serve.version>
I will move to formal release when serve verification is finished

2024-06-05 10:50 UTC, LiekeSchoenmaker commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctionsTest.java
> +    public List<ProtectEvidence> createProtectEvidenceList(@NotNull EvidenceLevel level, @NotNull EvidenceDirection direction) {
updated

2024-06-05 10:59 UTC, LiekeSchoenmaker commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/ExampleAnalysisTestFactory.java
> +                        .treatmentApproachesTherapy(Sets.newHashSet())
I have solved it in this class. However, this should be further incorporated into the whole project. I will updated when I see one

2024-06-05 10:59 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/algo/ProtectAlgo.java
> +        return updatedForTrials;
Blacklisted is moved to SERVE, so I have removed it from this place

2024-06-05 11:01 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
> +                    if (Genes.MSI_GENES.contains(gene.gene())) {
done

2024-06-05 11:03 UTC, LiekeSchoenmaker commented on protect/src/test/java/com/hartwig/oncoact/protect/evidence/VirusEvidenceTest.java
> +        ;
done

2024-06-11 14:12 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctions.java
> +                Set<String> treatmentApproaches = extractCombinedTreatmentApproaches(evidence.treatment().treatmentApproachesDrugClass(),
good catch, I have added an extra if statement

2024-06-11 14:15 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctions.java
> +                if (!hasHigherOrEqualEvidenceForEventAndTrial(trialEvidences, evidence) && !trial.equals(Strings.EMPTY)) {
good point, I have implemented it

2024-06-11 14:34 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/protect/ProtectEvidenceFile.java
> +            throw new IllegalStateException("An actionable event cannot be both a treatment and clinical trial");
what should we log here? You want log a specific clinicalTrial or Treatment for every entry I assume?

2024-06-11 14:36 UTC, LiekeSchoenmaker commented on patient-reporter/src/test/java/com/hartwig/oncoact/patientreporter/cfreport/chapters/analysed/ClinicalEvidenceFunctionsTest.java
> +        evidences.add(createProtectEvidence(level, direction));
Update it. I will do it whenever I see it

2024-06-11 14:38 UTC, LiekeSchoenmaker commented on protect/src/main/java/com/hartwig/oncoact/protect/evidence/VariantEvidence.java
>                  .eventIsHighDriver(driverInterpretation == null ? null : EvidenceDriverLikelihood.interpretVariant(driverInterpretation))
exists in PersonalizedEvidenceFactory.evidenceBuilder

2024-06-12 11:10 UTC, mdenburger approved these changes
Approved with some non-blocking remarks.

2024-06-12 11:10 UTC, mdenburger commented on common/src/main/java/com/hartwig/oncoact/protect/EvidenceComparator.java
> +                .compareTo(treatment2.treatmentApproachesTherapy().toString()) : 0;
Many branches are not covered by unit tests. Maybe expand the `ProtectEvidenceComparatorTest` a bit?

2024-06-12 11:10 UTC, mdenburger commented on common/src/main/java/com/hartwig/oncoact/util/ActionabilityIntervation.java
> +            throw new IllegalStateException("An actionable event cannot be both a treatment and clinical trial");
I'd include the clinical trail and treatment in the message to simplify debugging.

2024-06-12 11:10 UTC, mdenburger commented on pom.xml
> +        <serve.version>4.0.1-beta.2</serve.version>
Reminder to use a non-prerelease version before merging.

2024-06-12 14:43 UTC, mdenburger approved these changes

2024-06-13 10:47 UTC, merged