Dev 3397
hartwigmedical/oncoact pull request #8
Opened 2023-07-05 12:22 UTC by mvanniekerkHartwig

- Add `correction_json` property in favor of `sample_special_remark_tsv `, `comments`, `corrected_report`, and `corrected_report_extern`. 
- Many small refactoring fixes whenever I encountered something weird
- Fix a NPE in XML factory (found when testing the patient reporter on the COLO sample)

2023-07-06 14:05 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> -        String formattedTumorArrivalDate = tumorArrivalDate != null ? DateTimeFormatter.ofPattern("dd-MMM-yyyy").format(tumorArrivalDate) : "N/A";
Why do you have removed the N/A when the date is null?

2023-07-06 14:34 UTC, LiekeSchoenmaker commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/PatientReporterConfig.java
>              }
Now,  I see that the addRose boolean can also be removed. The rose TSV is always required in analysed reports like the orange.json

2023-07-06 14:42 UTC, LiekeSchoenmaker commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariant.java
Why do you remove the below six. I didn't follow how this is possible

2023-07-06 14:43 UTC, LiekeSchoenmaker commented
Looks good :) I added some small comments in your changes

2023-07-06 14:58 UTC, mvanniekerkHartwig commented on common/src/main/java/com/hartwig/oncoact/variant/ReportableVariant.java
They are already in the interface, so adding them in this class just creates unnecessary duplication.

2023-07-07 07:34 UTC, LiekeSchoenmaker approved these changes

2023-07-07 08:09 UTC, mdenburger requested changes

2023-07-07 08:09 UTC, mdenburger commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/algo/AnalysedPatientReporter.java
> +                .comments(Optional.ofNullable(reportData.correction()).map(Correction::specialRemark))
Should map to `Correcttion::comments`

2023-07-07 08:09 UTC, mdenburger commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/qcfail/QCFailReportData.java
> +        Correction correction = correctionJson != null ? Correction.read(correctionJson) : null;
Using `var` here would make the code slightly more readable because all variable names will then align nicely.

2023-07-07 08:09 UTC, mdenburger commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/xml/XMLFactory.java
> +                    .valuePath(Map.of("value", Optional.ofNullable(reportableVariant.biallelic()).map(b -> Boolean.toString(b)).orElse("")))
Would be nice to cover this NPE fix with a unit test

2023-07-07 08:43 UTC, mvanniekerkHartwig commented on patient-reporter/src/main/java/com/hartwig/oncoact/patientreporter/xml/XMLFactory.java
> +                    .valuePath(Map.of("value", Optional.ofNullable(reportableVariant.biallelic()).map(b -> Boolean.toString(b)).orElse("")))
Surprisingly enough this code is "tested" by generating the output XML and promply throwing it away :)
I did manage to create a test for it, but it just verifies no NPE gets thrown.

2023-07-07 08:46 UTC, mdenburger approved these changes

2023-07-07 11:50 UTC, merged